# Generated by Django 4.0.3 on 2022-04-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5)),
                ('items', models.IntegerField(default=25)),
                ('collage_width', models.IntegerField(default=1000)),
                ('collage_height', models.IntegerField(default=1000)),
                ('art_width', models.IntegerField(default=200)),
                ('art_height', models.IntegerField(default=200)),
            ],
        ),
    ]
