# Generated by Django 4.0.3 on 2022-04-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_size_art_height_alter_size_art_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='art_height',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='size',
            name='art_width',
            field=models.IntegerField(default=200),
        ),
    ]
